use_frameworks!

platform :ios, '10.0'

target 'SparkVenders_Example' do
  pod 'SparkVenders', :path => '../'

  target 'SparkVenders_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
